### ISSUE TITLE
Keep file extension when rolling

### ISSUE THREAD

**Issue by nomiddlename** [nomiddlename/streamroller#11]
Prompted by this issue in log4js: https://github.com/nomiddlename/log4js-node/issues/450

Adding a '.1', '.2', etc to the filenames when rotating breaks some users ability to read the files easily due to changing the extension. There should be a configuration option to keep the extension, on both the rolling file stream and date rolling. Default behaviour should be the current behaviour though, to maintain backwards compatibility.

**Comment by cula** [comment]
I tried to fix this. Travis passed on my own fork. U can see it above. However, test cases failed at random in the travis build of pull request. I've no right to rerun it. Plz take an eye on it.

**Comment by nomiddlename** [comment]
Thanks @cula - would you be able to do the same thing for the DateRollingFileStream as well? Don't worry if you don't have time, I appreciate the effort you've already put in, I'll add it to my list of things to fix.

**Comment by cula** [comment]
@nomiddlename 
Sure, it's a small change.
I've make a new pull request to fix this. Please make a review.

**Comment by nomiddlename** [comment]
@cula 's fix pushed to NPM in version 0.6.0
