### ISSUE TITLE
Unintended Error in case of file write error

### ISSUE THREAD

**Issue by ms270169** [nomiddlename/streamroller#2]
If the file is not writeable, an unintended Error message *throw er; // Unhandled 'error' event* is printed on console. 

I can handle this error when setting a "error" handler on stream.theStream. I would prefer to set an error handler on stream instead of manipulation an inner property (theStream). I have also seen, that writing to this "invalid" stream ist possible without errors. But the written string never finds the way into the file (which is not writeable).

What's the intended error handling? Why you can call write to an unwriteable file without any errors?

**Comment by nomiddlename** [comment]
That's not something I've ever tested, to be honest, which explains why it's not doing what you expect. I'll take a look and see if I can come up with something sensible.

**Comment by nomiddlename** [comment]
Published to npm in v0.2.2 - you can now add an `error` handler to the streamroller stream.
